name: Build Alpine Ansible Docker Image

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build and Publish Docker image
        uses: saubermacherag/gpr-docker-publish@master
        with:
          DOCKERFILE_PATH: 'Dockerfile'
          BUILD_CONTEXT: './'
          CACHE: true
          DOCKERHUB_REPOSITORY: 'pinkrobin/docker-ansible-alpine'
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        env:
          REGISTRY_TOKEN: ${{ secrets.DOCKERHUB_PAT }}

